name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test_build_publish:
    runs-on: ubuntu-latest
    # Make sure the branch reference is 'main' as you've specified 'main' above in the on.push.branches section
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.1'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
